### ISSUE TITLE
Crashing when previewed any fanart

### ISSUE THREAD

**Issue by Sizano** [flexbooru/flexbooru-ap#20]
versionName: 0.9.2.c229
packName: onlymash.flexbooru.ap
CPU_ABI: armeabi-v7a
CPU_ABI2: armeabi
RADIO: unknown
SERIAL: 629038920815
SUPPORTED_32_BIT_ABIS: [Ljava.lang.String;@dcefa64
SUPPORTED_64_BIT_ABIS: [Ljava.lang.String;@3ec344cd
SUPPORTED_ABIS: [Ljava.lang.String;@3ba8f182
TAGS: release-keys
TYPE: user
UNKNOWN: unknown
USER: xiaoy
IS_DEBUGGABLE: false
TIME: 1447984237000
Exception:+
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
	at android.view.ViewOverlay$OverlayViewGroup.add(ViewOverlay.java:164)
	at android.view.ViewGroupOverlay.add(ViewGroupOverlay.java:63)
	at android.app.EnterTransitionCoordinator.startRejectedAnimations(EnterTransitionCoordinator.java:598)
	at android.app.EnterTransitionCoordinator.startSharedElementTransition(EnterTransitionCoordinator.java:325)
	at android.app.EnterTransitionCoordinator.access$200(EnterTransitionCoordinator.java:42)
	at android.app.EnterTransitionCoordinator$5$1.run(EnterTransitionCoordinator.java:389)
	at android.app.ActivityTransitionCoordinator.startTransition(ActivityTransitionCoordinator.java:698)
	at android.app.EnterTransitionCoordinator$5.onPreDraw(EnterTransitionCoordinator.java:386)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2299)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1256)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6443)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
	at android.view.Choreographer.doCallbacks(Choreographer.java:603)
	at android.view.Choreographer.doFrame(Choreographer.java:572)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5576)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

**Comment by Sizano** [comment]
Preview and detail size already lowest option
